apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  labels:
    app: web
  namespace: production
spec:
  containers:
  - name: simple-webapp-color
    image: mmumshad/simple-webapp-color
    env:
      - name: APP_COLOR
        value: "red"