apiVersion: v1
kind: Service
metadata:
  name: service-pod
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30008