apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
    - name: mysql-volume
      image: mysql:8.0
      env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eaeazy
      - name: MYSQL_ROOT_PASSWORD
        value: password
      volumeMounts:
        - name: data-volume
          mountPath: /data-volume
  volumes:
    - name: data-volume
