apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
    - name: mysql-pv
      image: mysql:8.0
      env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eaeazy
      - name: MYSQL_ROOT_PASSWORD
        value: password
      volumeMounts:
        - name: my-pvc
          subPath: mysql
          mountPath: /var/lib/mysql
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-pvc
